import { useEffect, useMemo, useState } from 'react';
import { CalendarCheck, ChevronLeft, ChevronRight, CircleAlert, Clock3, RefreshCw, Users } from 'lucide-react';
import { attendance, employees, type AttendanceFeed, type AttendanceRecord, type Employee } from './lib/api';
import { useAuth } from './auth';

const weekdays = ['Sun', 'Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat'];
const key = (day: Date) => `${day.getFullYear()}-${String(day.getMonth() + 1).padStart(2, '0')}-${String(day.getDate()).padStart(2, '0')}`;
const dateOnly = (value: string) => new Date(`${value.slice(0, 10)}T00:00:00`);
const time = (value: string | null) => value ? new Date(value).toLocaleTimeString(undefined, { hour: 'numeric', minute: '2-digit' }) : '—';
const duration = (minutes: number | null) => minutes === null ? '—' : `${Math.floor(minutes / 60)}h ${minutes % 60}m`;

export default function Attendance() {
  const { user } = useAuth();
  const today = new Date();
  const [month, setMonth] = useState(() => new Date(today.getFullYear(), today.getMonth(), 1));
  const [selected, setSelected] = useState(() => key(new Date()));
  const [target, setTarget] = useState<string | null>(user?.role === 'ADMIN' ? null : user?.id ?? null);
  const [choices, setChoices] = useState<Employee[]>([]);
  const [feed, setFeed] = useState<AttendanceFeed | null>(null);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState('');
  const days = useMemo(() => { const first = new Date(month.getFullYear(), month.getMonth(), 1); const start = new Date(first); start.setDate(start.getDate() - start.getDay()); const last = new Date(month.getFullYear(), month.getMonth() + 1, 0); const end = new Date(last); end.setDate(end.getDate() + 6 - end.getDay()); return Array.from({ length: Math.round((end.getTime() - start.getTime()) / 86400000) + 1 }, (_, index) => new Date(start.getFullYear(), start.getMonth(), start.getDate() + index)); }, [month]);
  const start = key(days[0]); const end = key(days[days.length - 1]);
  const load = () => { setLoading(true); setError(''); const request = target ? attendance.employee(target, start, end) : attendance.mine(start, end); void request.then(setFeed).catch(() => setError('Unable to load attendance. Please try again.')).finally(() => setLoading(false)); };
  useEffect(() => { if (user?.role !== 'ADMIN') setTarget(user?.id ?? null); }, [user?.id, user?.role]);
  useEffect(() => { const loadChoices = async () => { try { if (user?.role === 'MANAGER') setChoices(await employees.directReports()); if (user?.role === 'ADMIN') setChoices((await employees.list()).filter((employee) => employee.role !== 'ADMIN' && employee.is_active)); } catch { setChoices([]); } }; void loadChoices(); }, [user?.role]);
  useEffect(() => { if (user?.role !== 'ADMIN' || target) load(); }, [target, start, end]);
  const record = feed?.records.find((item) => item.attendance_date === selected); const holiday = feed?.holidays.find((item) => item.date === selected); const selectedEmployee = feed?.employee;
  return <main className="workspace-page attendance-workspace"><header className="page-header attendance-page-header"><div><p className="eyebrow">Workday history</p><h1>Attendance</h1><p className="muted">Read-only regular workday attendance and approved attendance data.</p></div><button className="button-secondary" type="button" disabled={loading} onClick={load}><RefreshCw size={16} className={loading ? 'spin' : ''} /> Refresh</button></header>
    {user?.role === 'ADMIN' && <div className="attendance-selector"><Users size={17} /><label htmlFor="attendance-subject">View employee<select id="attendance-subject" value={target ?? ''} onChange={(event) => setTarget(event.target.value || null)}><option value="">Select an employee or manager</option>{choices.map((employee) => <option key={employee.id} value={employee.id}>{employee.full_name} · {employee.employee_code}</option>)}</select></label></div>}
    {user?.role === 'MANAGER' && <div className="attendance-selector"><Users size={17} /><label htmlFor="attendance-subject">View attendance<select id="attendance-subject" value={target ?? user?.id ?? ''} onChange={(event) => setTarget(event.target.value)}><option value={user?.id ?? ''}>My attendance</option>{choices.map((employee) => <option key={employee.id} value={employee.id}>{employee.full_name} · {employee.employee_code}</option>)}</select></label></div>}
    {error && <div className="calendar-error error" role="alert"><CircleAlert size={17} /><span>{error}</span><button type="button" className="button-secondary button-small" onClick={load}>Try again</button></div>}
    {user?.role === 'ADMIN' && !target ? <div className="attendance-empty"><Users size={24} /><h2>Select an attendance subject</h2><p>Administrators can view employee and manager attendance but do not have their own attendance record.</p></div> : <section className="attendance-layout"><section className="attendance-month-card"><header className="calendar-toolbar"><div className="calendar-period-navigation"><button type="button" className="button-secondary calendar-icon-button" aria-label="Previous month" onClick={() => setMonth(new Date(month.getFullYear(), month.getMonth() - 1, 1))}><ChevronLeft size={18} /></button><h2>{month.toLocaleDateString(undefined, { month: 'long', year: 'numeric' })}</h2><button type="button" className="button-secondary calendar-icon-button" aria-label="Next month" onClick={() => setMonth(new Date(month.getFullYear(), month.getMonth() + 1, 1))}><ChevronRight size={18} /></button></div><button type="button" className="button-secondary button-small" onClick={() => { const now = new Date(); setMonth(new Date(now.getFullYear(), now.getMonth(), 1)); setSelected(key(now)); }}>Today</button></header><div className="calendar-weekdays">{weekdays.map((day) => <span key={day}>{day}</span>)}</div><div className="attendance-grid">{days.map((day) => { const dayKey = key(day); const item = feed?.records.find((value) => value.attendance_date === dayKey); const closed = feed?.holidays.find((value) => value.date === dayKey); return <button key={dayKey} type="button" className={`attendance-day ${day.getMonth() !== month.getMonth() ? 'outside' : ''} ${dayKey === key(today) ? 'today' : ''} ${dayKey === selected ? 'selected' : ''} ${item?.status?.toLowerCase() ?? ''} ${closed ? 'holiday' : ''}`} onClick={() => setSelected(dayKey)}><span>{day.getDate()}</span>{closed ? <small>{closed.name}</small> : item ? <small>{item.status === 'PRESENT' ? 'Present' : item.status === 'LEAVE' ? 'Leave' : 'Absent'}</small> : null}</button>; })}</div></section><aside className="attendance-detail"><header><div><p className="eyebrow">Selected day</p><h2>{dateOnly(selected).toLocaleDateString(undefined, { weekday: 'long', month: 'long', day: 'numeric' })}</h2>{selectedEmployee && <small>{selectedEmployee.full_name} · {selectedEmployee.employee_code}</small>}</div><CalendarCheck size={19} /></header>{loading ? <p className="muted">Loading attendance…</p> : holiday ? <div className="attendance-empty"><CalendarCheck size={22} /><h3>Non-working day</h3><p>{holiday.name}</p></div> : record ? <AttendanceDetail record={record} /> : <div className="attendance-empty"><Clock3 size={22} /><h3>No attendance record</h3><p>This is not an absence. No record has been created for this date.</p></div>}</aside></section>}
  </main>;
}

function AttendanceDetail({ record }: { record: AttendanceRecord }) { return <dl className="attendance-facts"><div><dt>Status</dt><dd>{record.status}</dd></div>{record.status === 'PRESENT' && <><div><dt>Check in</dt><dd>{time(record.regular_check_in_at)}</dd></div><div><dt>Check out</dt><dd>{time(record.regular_check_out_at)}</dd></div><div><dt>Late arrival</dt><dd>{record.late_minutes === null ? '—' : record.late_minutes ? `${record.late_minutes} minutes late` : 'On time'}</dd></div><div><dt>Regular worked time</dt><dd>{duration(record.worked_minutes)}</dd></div></>}{record.status === 'LEAVE' && <div><dt>Leave type</dt><dd>{record.leave_type ?? 'Approved leave'}</dd></div>}</dl>; }
