import { useEffect, useState } from 'react';
import { ApiError, chat, ChatConversation, ChatMessage, employees, Employee } from './lib/api';
import { useAuth } from './auth';

export default function Chat() {
  const { user } = useAuth(); const [items,setItems]=useState<ChatConversation[]>([]); const [selected,setSelected]=useState<ChatConversation|null>(null); const [messages,setMessages]=useState<ChatMessage[]>([]); const [people,setPeople]=useState<Employee[]>([]); const [query,setQuery]=useState(''); const [text,setText]=useState(''); const [error,setError]=useState('');
  const load=async()=>{ try { setItems(await chat.conversations()); } catch { setError('Chat is unavailable.'); } };
  useEffect(()=>{ void load(); },[]);
  useEffect(()=>{ if(!selected)return; void chat.messages(selected.id).then(setMessages).catch(()=>setError('Unable to load messages.')); void chat.read(selected.id); },[selected?.id]);
  useEffect(()=>{ const token=sessionStorage.getItem('infotech_token'); if(!token)return; const base=(import.meta.env.VITE_API_BASE_URL??'http://localhost:8001').replace(/^http/,'ws'); const socket=new WebSocket(`${base}/api/v1/chat/ws?token=${encodeURIComponent(token)}`); socket.onmessage=(event)=>{ try { const value=JSON.parse(event.data); if(value?.type!=='message.created'||!value.message)return; setMessages(current=>current.some(m=>m.id===value.message.id)?current:[...current,value.message]); void load(); } catch { /* Ignore malformed events. */ } }; return()=>socket.close(); },[]);
  useEffect(()=>{ if(query.length<2){setPeople([]);return;} void employees.search(query).then(setPeople).catch(()=>setPeople([])); },[query]);
  const open=async(c:ChatConversation)=>{setSelected(c);setError('');};
  const direct=async(id:string)=>{try{const c=await chat.direct(id); await load(); await open(c); setQuery('');setPeople([]);}catch(e){setError(e instanceof ApiError?e.message:'Unable to start chat.');}};
  const send=async(e:React.FormEvent)=>{e.preventDefault();if(!selected||!text.trim())return;try{const m=await chat.send(selected.id,text);setMessages(x=>[...x,m]);setText('');await load();}catch(e){setError(e instanceof ApiError?e.message:'Unable to send message.');}};
  return <main className="workspace-page"><h1>Chat</h1>{error&&<p className="error">{error}</p>}<div className="chat-layout"><aside className="card"><label>New direct chat<input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search employees"/></label>{people.filter(p=>p.id!==user?.id).map(p=><button key={p.id} onClick={()=>void direct(p.id)}>{p.full_name} · {p.employee_code}</button>)}<hr/>{items.map(c=><button key={c.id} onClick={()=>void open(c)}>{c.name||`${c.type} conversation`}{c.unread_count>0&&<b className="badge">{c.unread_count}</b>}<small>{c.last_message?.content}</small></button>)}</aside><section className="card">{selected?<><h2>{selected.name||'Direct conversation'}</h2><div className="messages">{messages.map(m=><p key={m.id} className={m.sender_employee_id===user?.id?'sent':'received'}>{m.content}<small>{new Date(m.created_at).toLocaleString()}</small></p>)}</div><form onSubmit={send}><input value={text} maxLength={4000} onChange={e=>setText(e.target.value)} placeholder="Write a message"/><button>Send</button></form></>:<p className="muted">Select a conversation or search for an employee to begin.</p>}</section></div></main>;
}
