import { useEffect, useState } from 'react';
import { employees, type Employee } from './lib/api';

const empty = { employee_code: '', full_name: '', company_email: '', role: 'EMPLOYEE', designation: '', department: '', manager_id: '' };
export default function Employees() {
  const [list, setList] = useState<Employee[]>([]), [form, setForm] = useState<any>(empty), [editing, setEditing] = useState<Employee | null>(null), [error, setError] = useState(''), [temp, setTemp] = useState('');
  const load = async (q = '') => { try { setList(q ? await employees.search(q) : await employees.list()); } catch { setError('Unable to load employees.'); } };
  useEffect(() => { load(); }, []);
  const managers = list.filter(x => x.role === 'MANAGER');
  return <section><h1>Employee Management</h1><p className="muted">Google Workspace provisioning will be integrated in a later phase.</p><input placeholder="Search employees" onChange={e => load(e.target.value)} />
    <form className="card" onSubmit={async e => { e.preventDefault(); try { const r = await employees.create({ ...form, manager_id: form.manager_id || null }); setTemp(r.temporary_password); setForm(empty); await load(); } catch { setError('Unable to create employee.'); } }}>
      <h2>Add employee</h2>{Object.entries(form).map(([key, value]) => key === 'role' ? <select key={key} value={String(value)} onChange={e => setForm({ ...form, role: e.target.value })}><option>ADMIN</option><option>MANAGER</option><option>EMPLOYEE</option></select> : key === 'manager_id' ? <select key={key} value={String(value)} onChange={e => setForm({ ...form, manager_id: e.target.value })}><option value="">No manager</option>{managers.map(m => <option value={m.id}>{m.full_name} · {m.employee_code}</option>)}</select> : <input key={key} placeholder={key} value={String(value)} onChange={e => setForm({ ...form, [key]: e.target.value })} />)}<button>Add employee</button>
    </form>{temp && <div className="response">Development-only onboarding credential: <b>{temp}</b><button onClick={() => setTemp('')}>Dismiss</button></div>}{error && <p className="muted">{error}</p>}
    {editing && <form className="card" onSubmit={async e => { e.preventDefault(); await employees.update(editing.id, { full_name: editing.full_name, role: editing.role, designation: editing.designation, department: editing.department, manager_id: editing.manager_id, is_active: editing.is_active }); setEditing(null); load(); }}><h2>Edit {editing.full_name}</h2><input value={editing.full_name} onChange={e => setEditing({ ...editing, full_name: e.target.value })}/><select value={editing.role} onChange={e => setEditing({ ...editing, role: e.target.value })}><option>ADMIN</option><option>MANAGER</option><option>EMPLOYEE</option></select><input value={editing.designation} onChange={e => setEditing({ ...editing, designation: e.target.value })}/><input value={editing.department} onChange={e => setEditing({ ...editing, department: e.target.value })}/><select value={editing.manager_id ?? ''} onChange={e => setEditing({ ...editing, manager_id: e.target.value || null })}><option value="">No manager</option>{managers.filter(m => m.id !== editing.id).map(m => <option value={m.id}>{m.full_name} · {m.employee_code}</option>)}</select><label><input type="checkbox" checked={editing.is_active} onChange={e => setEditing({ ...editing, is_active: e.target.checked })}/> Active</label><button>Save changes</button></form>}
    {!list.length ? <p className="muted">No employees found.</p> : <table><thead><tr><th>Code</th><th>Name</th><th>Email</th><th>Role</th><th>Designation</th><th>Department</th><th>Status</th><th/></tr></thead><tbody>{list.map(x => <tr><td>{x.employee_code}</td><td>{x.full_name}</td><td>{x.company_email}</td><td>{x.role}</td><td>{x.designation}</td><td>{x.department}</td><td>{x.is_active ? 'Active' : 'Inactive'}</td><td><button onClick={() => setEditing(x)}>Edit</button><button onClick={async () => { await employees.update(x.id, { is_active: !x.is_active }); load(); }}>{x.is_active ? 'Deactivate' : 'Reactivate'}</button></td></tr>)}</tbody></table>}</section>;
}
