import { useEffect, useState } from 'react';
import { ApiError, type HalfDayPeriod, type LeaveRequest, type LeaveType, leaves } from './lib/api';
import { useAuth } from './auth';

type Props = { onNotificationChange: () => void };
const labels: Record<LeaveType, string> = { CASUAL: 'Casual', MEDICAL: 'Medical / Sick', EMERGENCY: 'Emergency', DAY_OFF: 'Day Off' };
const formatDate = (value: string) => new Date(`${value}T00:00:00`).toLocaleDateString();
const range = (leave: LeaveRequest) => leave.start_date === leave.end_date ? formatDate(leave.start_date) : `${formatDate(leave.start_date)} – ${formatDate(leave.end_date)}`;
function message(error: unknown) { if (!(error instanceof ApiError)) return 'Unable to reach the EMS service. Please try again.'; if (error.status === 403) return 'You are not authorized to perform that action.'; if (error.status === 409) return 'This leave request has already changed. Latest data was loaded.'; if (error.status === 422) return 'Please check the leave details and try again.'; return 'Unable to complete the request. Please try again.'; }
function Status({ status }: { status: LeaveRequest['status'] }) { return <span className={`status status-${status.toLowerCase()}`}>{status[0] + status.slice(1).toLowerCase()}</span>; }

function LeaveList({ items, team, decide }: { items: LeaveRequest[]; team: boolean; decide: (leave: LeaveRequest, action: 'approve' | 'reject', note?: string) => void }) {
  const [rejecting, setRejecting] = useState<string | null>(null); const [note, setNote] = useState(''); const [busy, setBusy] = useState<string | null>(null);
  useEffect(() => { setBusy(null); }, [items]);
  return <div className="leave-list">{items.map(leave => <article className="leave-row" key={leave.id}><div><strong>{team ? `${leave.employee.full_name} · ${leave.employee.employee_code}` : labels[leave.leave_type]}</strong><p>{team && labels[leave.leave_type]} · {range(leave)}</p><small>{leave.duration === 'HALF_DAY' ? `Half Day · ${leave.half_day_period === 'MORNING' ? 'Morning' : 'Afternoon'}` : 'Full Day'} · Submitted {formatDate(leave.created_at)}</small></div><div className="leave-details"><Status status={leave.status} /><p>{leave.reason}</p>{leave.decision_note && <small>Decision note: {leave.decision_note}</small>}{leave.decision_source === 'AUTOMATIC_POLICY' && <small>Automatically approved by policy</small>}{team && leave.status === 'PENDING' && leave.approval_required && <div className="decision-actions">{rejecting === leave.id ? <><label htmlFor={`note-${leave.id}`}>Rejection note (optional)</label><textarea id={`note-${leave.id}`} value={note} onChange={event => setNote(event.target.value)} /><button type="button" className="ghost" onClick={() => { setRejecting(null); setNote(''); }}>Cancel</button><button type="button" disabled={busy === leave.id} onClick={() => { setBusy(leave.id); decide(leave, 'reject', note); }}>Confirm rejection</button></> : <><button type="button" disabled={busy === leave.id} onClick={() => { setBusy(leave.id); decide(leave, 'approve'); }}>{busy === leave.id ? 'Approving…' : 'Approve'}</button><button type="button" className="ghost" disabled={busy === leave.id} onClick={() => setRejecting(leave.id)}>Reject</button></>}</div>}</div></article>)}</div>;
}

export default function Leave({ onNotificationChange }: Props) {
  const { user } = useAuth(); const [mine, setMine] = useState<LeaveRequest[]>([]); const [team, setTeam] = useState<LeaveRequest[]>([]); const [tab, setTab] = useState<'mine' | 'team'>('mine');
  const [leaveType, setLeaveType] = useState<LeaveType>('CASUAL'); const [startDate, setStartDate] = useState(''); const [endDate, setEndDate] = useState(''); const [period, setPeriod] = useState<HalfDayPeriod | ''>(''); const [reason, setReason] = useState('');
  const [loading, setLoading] = useState(true); const [submitting, setSubmitting] = useState(false); const [error, setError] = useState(''); const [feedback, setFeedback] = useState('');
  const load = async () => { setLoading(true); setError(''); try { setMine(await leaves.mine()); if (user?.role === 'MANAGER') setTeam(await leaves.team()); } catch (caught) { setError(message(caught)); } finally { setLoading(false); } };
  useEffect(() => { void load(); }, [user?.role]);
  const dayOff = leaveType === 'DAY_OFF';
  const submit = async (event: React.FormEvent) => { event.preventDefault(); setFeedback(''); if (!startDate || !reason || (!dayOff && !endDate) || (dayOff && !period)) { setError('Complete all required leave details.'); return; } const end = dayOff ? startDate : endDate; if (end < startDate) { setError('End date must be on or after start date.'); return; } setSubmitting(true); setError(''); try { const created = await leaves.create({ leave_type: leaveType, start_date: startDate, end_date: end, duration: dayOff ? 'HALF_DAY' : 'FULL_DAY', ...(dayOff ? { half_day_period: period as HalfDayPeriod } : {}), reason }); setFeedback(created.status === 'APPROVED' ? 'Medical leave recorded and automatically approved.' : 'Leave request submitted for Manager review.'); setReason(''); setStartDate(''); setEndDate(''); setPeriod(''); await load(); onNotificationChange(); } catch (caught) { setError(message(caught)); } finally { setSubmitting(false); } };
  const decide = async (leave: LeaveRequest, action: 'approve' | 'reject', note?: string) => { try { if (action === 'approve') await leaves.approve(leave.id); else await leaves.reject(leave.id, note); setFeedback(`Leave ${action === 'approve' ? 'approved' : 'rejected'}.`); await load(); onNotificationChange(); } catch (caught) { setError(message(caught)); await load(); } };
  return <main className="workspace-page"><header><div><p className="eyebrow">Leave management</p><h1>Leave</h1></div><button className="ghost" onClick={() => void load()} disabled={loading}>Refresh</button></header><div className="leave-layout"><section><div className="policy card"><h2>Leave guidance</h2><ul><li>Casual — Manager approval required</li><li>Medical / Sick — Automatically approved; Manager notified for awareness</li><li>Emergency — Manager approval required</li><li>Day Off — Half-day; Manager approval required</li></ul><small>Leave entitlement and accrual balances are not yet finalized.</small></div><form className="card" onSubmit={submit}><h2>Apply leave</h2><label htmlFor="leave-type">Leave type</label><select id="leave-type" value={leaveType} onChange={event => { setLeaveType(event.target.value as LeaveType); setPeriod(''); }}><option value="CASUAL">Casual</option><option value="MEDICAL">Medical / Sick</option><option value="EMERGENCY">Emergency</option><option value="DAY_OFF">Day Off</option></select><label htmlFor="leave-start">{dayOff ? 'Date' : 'Start date'}</label><input id="leave-start" type="date" value={startDate} onChange={event => setStartDate(event.target.value)} required />{!dayOff && <><label htmlFor="leave-end">End date</label><input id="leave-end" type="date" value={endDate} onChange={event => setEndDate(event.target.value)} required /></>}{dayOff && <><label htmlFor="half-day-period">Half-day period</label><select id="half-day-period" value={period} onChange={event => setPeriod(event.target.value as HalfDayPeriod)} required><option value="">Select period</option><option value="MORNING">Morning</option><option value="AFTERNOON">Afternoon</option></select></>}<label htmlFor="leave-reason">Reason</label><textarea id="leave-reason" value={reason} onChange={event => setReason(event.target.value)} required /><button disabled={submitting}>{submitting ? 'Submitting…' : 'Submit leave request'}</button></form></section><section className="card"><div className="tabs"><button type="button" className={tab === 'mine' ? '' : 'ghost'} onClick={() => setTab('mine')}>My Leave</button>{user?.role === 'MANAGER' && <button type="button" className={tab === 'team' ? '' : 'ghost'} onClick={() => setTab('team')}>Team Leave</button>}</div>{error && <p className="error" role="alert">{error}</p>}{feedback && <p className="success" role="status">{feedback}</p>}{loading ? <p className="muted">Loading leave requests…</p> : tab === 'mine' ? mine.length ? <LeaveList items={mine} team={false} decide={decide} /> : <p className="muted">You have no leave requests yet.</p> : team.length ? <LeaveList items={team} team decide={decide} /> : <p className="muted">Your direct reports have no leave requests.</p>}</section></div></main>;
}
