import React from'react';import{createRoot}from'react-dom/client';import{BrowserRouter,NavLink,Routes,Route}from'react-router-dom';import{MessageCircle,CalendarDays,Palmtree,Inbox,Brain,User}from'lucide-react';import'./style.css';
const nav=[['/','Chat',MessageCircle],['/calendar','Calendar',CalendarDays],['/leave','Leave',Palmtree],['/inbox','Inbox',Inbox],['/agent','Agent',Brain],['/profile','Profile',User]] as const;
const Chat=()=> <section><h1>Team conversations</h1><input placeholder="Search conversations"/><div className="split"><aside><b>Arjun Mehta</b><p className="muted">Online · Product sync</p><b>Engineering</b><p className="muted">8 members</p></aside><article><h2>Engineering</h2><p><b>Maya</b> The release notes are ready.</p><p><b>You</b> Great, I’ll review them today.</p><textarea placeholder="Write a message…"/></article></div></section>;
const Calendar=()=> <section><h1>September 2026</h1><div className="calendar">{Array.from({length:30},(_,i)=><div key={i}><b>{i+1}</b>{i===10&&<small>Team meeting</small>}{i===19&&<small>Holiday</small>}</div>)}</div><aside className="agenda"><h3>Upcoming</h3><p>10 Sep · Engineering sync</p><p>19 Sep · InfoTech holiday</p></aside></section>;
const Leave=()=> <section><h1>Leave</h1><div className="cards">{[['Casual Leave','8 days'],['Medical / Sick Leave','6 days'],['Emergency Leave','2 days'],['Day-off','1 day']].map(x=><div><span>{x[0]}</span><b>{x[1]}</b></div>)}</div><h2>Apply leave</h2><div className="form"><select><option>Casual Leave</option></select><input placeholder="Dates"/><button>Submit request</button></div><h2>Recent requests</h2><p>Casual Leave · 12–13 Sep · Pending approval</p></section>;
const InboxPage=()=> <section><h1>Inbox</h1><div className="tabs">Requests · Updates</div><article className="card"><b>Leave request from Priya N.</b><p>Medical / Sick Leave · 2 days</p><button>Approve</button> <button className="ghost">Reject</button></article><p className="muted">Your Casual Leave request is pending manager approval.</p></section>;
const Agent=()=> <section className="agent"><h1>Your InfoTech assistant</h1><p className="muted">Answers are grounded in InfoTech company policies and include sources.</p><div className="chips">{['Apply leave for 2 days','Schedule a meeting','Check leave balance','WFH policy'].map(x=><button>{x}</button>)}</div><article className="response"><b>Leave balance</b><p>You have 8 Casual Leave days remaining.</p><small>Source: InfoTech Leave & Attendance Policy · Page 12</small></article><textarea placeholder="Ask anything about work, policies, or leave…"/><button>Send</button></section>;
const Profile=()=> <section><h1>Profile</h1><div className="card"><h2>Avery Kumar</h2><p>avery.kumar@infotech.example</p><p>EMP-1042 · EMPLOYEE · Senior Engineer</p><p>Engineering · Manager: Maya Rao</p></div></section>;
function App(){return <div className="app"><nav><strong>IT</strong>{nav.map(([to,label,Icon])=><NavLink to={to}><Icon/><span>{label}</span></NavLink>)}<div className="avatar">AK</div></nav><main><Routes><Route path="/" element={<Chat/>}/><Route path="/calendar" element={<Calendar/>}/><Route path="/leave" element={<Leave/>}/><Route path="/inbox" element={<InboxPage/>}/><Route path="/agent" element={<Agent/>}/><Route path="/profile" element={<Profile/>}/></Routes></main></div>}createRoot(document.getElementById('root')!).render(<BrowserRouter><App/></BrowserRouter>);
