import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { createRoot } from 'react-dom/client';
import { BrowserRouter, NavLink, Routes, Route } from 'react-router-dom';
import { MessageCircle, CalendarDays, Palmtree, Inbox, Brain, User } from 'lucide-react';
import './style.css';
const nav = [['/', 'Chat', MessageCircle], ['/calendar', 'Calendar', CalendarDays], ['/leave', 'Leave', Palmtree], ['/inbox', 'Inbox', Inbox], ['/agent', 'Agent', Brain], ['/profile', 'Profile', User]];
const Chat = () => _jsxs("section", { children: [_jsx("h1", { children: "Team conversations" }), _jsx("input", { placeholder: "Search conversations" }), _jsxs("div", { className: "split", children: [_jsxs("aside", { children: [_jsx("b", { children: "Arjun Mehta" }), _jsx("p", { className: "muted", children: "Online \u00B7 Product sync" }), _jsx("b", { children: "Engineering" }), _jsx("p", { className: "muted", children: "8 members" })] }), _jsxs("article", { children: [_jsx("h2", { children: "Engineering" }), _jsxs("p", { children: [_jsx("b", { children: "Maya" }), " The release notes are ready."] }), _jsxs("p", { children: [_jsx("b", { children: "You" }), " Great, I\u2019ll review them today."] }), _jsx("textarea", { placeholder: "Write a message\u2026" })] })] })] });
const Calendar = () => _jsxs("section", { children: [_jsx("h1", { children: "September 2026" }), _jsx("div", { className: "calendar", children: Array.from({ length: 30 }, (_, i) => _jsxs("div", { children: [_jsx("b", { children: i + 1 }), i === 10 && _jsx("small", { children: "Team meeting" }), i === 19 && _jsx("small", { children: "Holiday" })] }, i)) }), _jsxs("aside", { className: "agenda", children: [_jsx("h3", { children: "Upcoming" }), _jsx("p", { children: "10 Sep \u00B7 Engineering sync" }), _jsx("p", { children: "19 Sep \u00B7 InfoTech holiday" })] })] });
const Leave = () => _jsxs("section", { children: [_jsx("h1", { children: "Leave" }), _jsx("div", { className: "cards", children: [['Casual Leave', '8 days'], ['Medical / Sick Leave', '6 days'], ['Emergency Leave', '2 days'], ['Day-off', '1 day']].map(x => _jsxs("div", { children: [_jsx("span", { children: x[0] }), _jsx("b", { children: x[1] })] })) }), _jsx("h2", { children: "Apply leave" }), _jsxs("div", { className: "form", children: [_jsx("select", { children: _jsx("option", { children: "Casual Leave" }) }), _jsx("input", { placeholder: "Dates" }), _jsx("button", { children: "Submit request" })] }), _jsx("h2", { children: "Recent requests" }), _jsx("p", { children: "Casual Leave \u00B7 12\u201313 Sep \u00B7 Pending approval" })] });
const InboxPage = () => _jsxs("section", { children: [_jsx("h1", { children: "Inbox" }), _jsx("div", { className: "tabs", children: "Requests \u00B7 Updates" }), _jsxs("article", { className: "card", children: [_jsx("b", { children: "Leave request from Priya N." }), _jsx("p", { children: "Medical / Sick Leave \u00B7 2 days" }), _jsx("button", { children: "Approve" }), " ", _jsx("button", { className: "ghost", children: "Reject" })] }), _jsx("p", { className: "muted", children: "Your Casual Leave request is pending manager approval." })] });
const Agent = () => _jsxs("section", { className: "agent", children: [_jsx("h1", { children: "Your InfoTech assistant" }), _jsx("p", { className: "muted", children: "Answers are grounded in InfoTech company policies and include sources." }), _jsx("div", { className: "chips", children: ['Apply leave for 2 days', 'Schedule a meeting', 'Check leave balance', 'WFH policy'].map(x => _jsx("button", { children: x })) }), _jsxs("article", { className: "response", children: [_jsx("b", { children: "Leave balance" }), _jsx("p", { children: "You have 8 Casual Leave days remaining." }), _jsx("small", { children: "Source: InfoTech Leave & Attendance Policy \u00B7 Page 12" })] }), _jsx("textarea", { placeholder: "Ask anything about work, policies, or leave\u2026" }), _jsx("button", { children: "Send" })] });
const Profile = () => _jsxs("section", { children: [_jsx("h1", { children: "Profile" }), _jsxs("div", { className: "card", children: [_jsx("h2", { children: "Avery Kumar" }), _jsx("p", { children: "avery.kumar@infotech.example" }), _jsx("p", { children: "EMP-1042 \u00B7 EMPLOYEE \u00B7 Senior Engineer" }), _jsx("p", { children: "Engineering \u00B7 Manager: Maya Rao" })] })] });
function App() { return _jsxs("div", { className: "app", children: [_jsxs("nav", { children: [_jsx("strong", { children: "IT" }), nav.map(([to, label, Icon]) => _jsxs(NavLink, { to: to, children: [_jsx(Icon, {}), _jsx("span", { children: label })] })), _jsx("div", { className: "avatar", children: "AK" })] }), _jsx("main", { children: _jsxs(Routes, { children: [_jsx(Route, { path: "/", element: _jsx(Chat, {}) }), _jsx(Route, { path: "/calendar", element: _jsx(Calendar, {}) }), _jsx(Route, { path: "/leave", element: _jsx(Leave, {}) }), _jsx(Route, { path: "/inbox", element: _jsx(InboxPage, {}) }), _jsx(Route, { path: "/agent", element: _jsx(Agent, {}) }), _jsx(Route, { path: "/profile", element: _jsx(Profile, {}) })] }) })] }); }
createRoot(document.getElementById('root')).render(_jsx(BrowserRouter, { children: _jsx(App, {}) }));
